name: Refresh README images (cache-bust)

on:
  schedule:
    - cron: '0 0 * * *'      # daily at 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  refresh-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update README cache-bust token
        run: |
          TIMESTAMP=$(date +%s)
          FILE=README.md
          sed -E -i "s/([?&])v=[0-9]+/\\1v=${TIMESTAMP}/g" "$FILE"
          sed -E -i "s@(https://github-readme-stats.vercel.app/[^)\"']+)@\\1&v=${TIMESTAMP}@g" "$FILE"
          sed -E -i "s@(https://github-readme-streak-stats.herokuapp.com[^)\"']+)@\\1&v=${TIMESTAMP}@g" "$FILE"
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add "$FILE"
            git commit -m "chore: refresh README images (cache-bust) - $TIMESTAMP"
            git push
          fi
